Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,5 +23,8 @@ jobs:
 
       - name: Install CI
         run: |
+          if [[ -z "$REDIS_HOST" || -z "$REDIS_PORT" || -z "$REDIS_PW" ]]; then
+            echo "Error: One or more environment variables missing."
+            exit 1
           pip install "tox>=4.0"
           tox
