Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,10 @@ jobs:
 
     name: Unit tests and code checks
     runs-on: ubuntu-latest
+    env:
+      REDIS_HOST: ${{ secrets.REDIS_HOST }}
+      REDIS_PORT: ${{ secrets.REDIS_PORT }}
+      REDIS_PW: ${{ secrets.REDIS_PW }}
 
     steps:
       - uses: actions/checkout@v3
@@ -17,11 +21,11 @@ jobs:
         with:
           python-version: "3.12"
 
-      - name: Set environment variables and install CI
-        env:
-          REDIS_HOST: ${{ secrets.REDIS_HOST }}
-          REDIS_PORT: ${{ secrets.REDIS_PORT }}
-          REDIS_PW: ${{ secrets.REDIS_PW }}
+      - name: Install CI
         run: |
-            pip install "tox>=4.0"
-            tox
+          # Check if environment variables are set
+          if [[ -z "$REDIS_HOST" || -z "$REDIS_PORT" || -z "$REDIS_PW" ]]; then
+          echo "Error: One or more environment variables missing."
+          exit 1
+          pip install "tox>=4.0"
+          tox
